<a href="https://colab.research.google.com/github/himanshuRepo/Introduction-to-PyTorch/blob/master/IntroductionToPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch**: It is a Python library that facilitates in performing scientific computation.
* Similar to Numpy library but ***designed*** for GPU
* Uses ***Tensor*** as its core data structure similar to Numpy array
* Uses concepts of ***object-oriented programming***
* ***Popular*** for deep learning research:
  * Dynamic computational graphs
  * Easy to move data to and from a GPU
  * It keeps things simple and in ***Pythonic*** way







# Importing Pytorch library

In [0]:
import torch

# Creating a tensor variable

In [0]:
t = torch.Tensor()

In [3]:
# Checking the data type of the created tensor
t.dtype

torch.float32

In [5]:
# Checking the device of the created tensor
t.device

device(type='cpu')

In [6]:
# Checking the availability of the GPU
torch.cuda.is_available()

True

In [7]:
# defining the device variable for GPU
deviceGPU = torch.device('cuda')
deviceGPU

device(type='cuda')

In [10]:
# Moving the variable to GPU
tc = t.to(deviceGPU)
tc.device


device(type='cuda', index=0)

In [11]:
t.device

device(type='cpu')

* **Remember**: Operations between tensors can be performed if they are on the same device and have data type

## Four ways to create a tensor variable with data

In [12]:
# Defining some data
import numpy as np
data = np.array([7,8,9])
print(data)

[7 8 9]


In [13]:
# Checking the data type of the data
type(data)

numpy.ndarray

In [18]:
# I: First way
t1 = torch.Tensor(data)
print(t1)
print(t1.dtype)

tensor([7., 8., 9.])
torch.float32


In [21]:
# II: Second way
t2 = torch.tensor(data)
print(t2)
print(t2.dtype)

tensor([7, 8, 9])
torch.int64


In [20]:
# III: Third way
t3 = torch.as_tensor(data)
print(t3)
print(t3.dtype)

tensor([7, 8, 9])
torch.int64


In [19]:
# IV: Fourth way
t4 = torch.from_numpy(data)
print(t4)
print(t4.dtype)

tensor([7, 8, 9])
torch.int64


In [22]:
# Checking the device of the tensor variable
t4.device

device(type='cpu')

In [24]:
# Changing the device as GPU 
tc4 = t4.to(deviceGPU)
tc4.device  

device(type='cuda', index=0)

In [26]:
# Defining the data type of tensor variable expicitly: Possible with II, III, and IV
t5 = torch.tensor(data, dtype=torch.float32)
print(t5)
print(t5.dtype)

tensor([7., 8., 9.])
torch.float32


## Tensors with shared and separate memory

In [27]:
# Data sample 
data1 = data
print(data1)
data2=data.copy()
print(data2)

[7 8 9]
[7 8 9]


In [28]:
# Changing a value of data variable
data[1]=3
print(data)
print(data1)
print(data2)

[7 3 9]
[7 3 9]
[7 8 9]


In [29]:
# Changes in the tensor variables created using data above
print(t1) # I method: No value changes => Creates a separate memory for itself
print(t2) # II method: No value changes => Creates a separate memory for itself
print(t3) # III method: Value changes => Shares the memory of the data
print(t4) # IV method: Value changes => Shares the memory of the data

tensor([7., 8., 9.])
tensor([7, 8, 9])
tensor([7, 3, 9])
tensor([7, 3, 9])


# Ways to create a tensor variable with default values

In [30]:
# Using the eye function to create Identity tensor
t6 = torch.eye(2)
print(t6)

tensor([[1., 0.],
        [0., 1.]])


In [31]:
# Using the zeros function
t7 = torch.zeros([2,2])
print(t7)

tensor([[0., 0.],
        [0., 0.]])


In [32]:
# Using the ones function
t8 = torch.ones(2,2)
print(t8)

tensor([[1., 1.],
        [1., 1.]])


In [33]:
# Using the rand function
t9 = torch.rand(3,4)
print(t9)

tensor([[0.4885, 0.8982, 0.2852, 0.8391],
        [0.9299, 0.0885, 0.6594, 0.1326],
        [0.2563, 0.7079, 0.6505, 0.0451]])


#Some properties and operations on a tensor variable

In [34]:
print(t9.size())        # Determines shape of tensor variable
print(t9.shape)         # Determines shape of tensor variable
print(t9.numel())       # Determines number of values in tensor variable
# print(torch.tensor(t9.shape).prod().item())

torch.Size([3, 4])
torch.Size([3, 4])
12


## Reshaping operation

In [35]:
t10 = t9.reshape([2,6])
print(t10)
print(t10.shape)
print(t9.reshape(3,4))
print(t9.view(3,4))

tensor([[0.4885, 0.8982, 0.2852, 0.8391, 0.9299, 0.0885],
        [0.6594, 0.1326, 0.2563, 0.7079, 0.6505, 0.0451]])
torch.Size([2, 6])
tensor([[0.4885, 0.8982, 0.2852, 0.8391],
        [0.9299, 0.0885, 0.6594, 0.1326],
        [0.2563, 0.7079, 0.6505, 0.0451]])
tensor([[0.4885, 0.8982, 0.2852, 0.8391],
        [0.9299, 0.0885, 0.6594, 0.1326],
        [0.2563, 0.7079, 0.6505, 0.0451]])


## Squeezing and unsqueezing operation

In [41]:
t11 = t9.reshape([1,12])
print(t11)
print(t11.shape)

# Squeezing operation
t12 = t11.squeeze()           
print(t12)
print(t12.shape)

# Unsqueezing operation along first axis/dimension (row-wise for 2d Tensor)
t13 = t12.unsqueeze(dim=0)   
print(t13)
print(t13.shape)

# Unsqueezing operation along second axis/dimension (column-wise for 2d Tensor)
t13 = t12.unsqueeze(dim=1)   
print(t13)
print(t13.shape)

tensor([[0.4885, 0.8982, 0.2852, 0.8391, 0.9299, 0.0885, 0.6594, 0.1326, 0.2563,
         0.7079, 0.6505, 0.0451]])
torch.Size([1, 12])
tensor([0.4885, 0.8982, 0.2852, 0.8391, 0.9299, 0.0885, 0.6594, 0.1326, 0.2563,
        0.7079, 0.6505, 0.0451])
torch.Size([12])
tensor([[0.4885, 0.8982, 0.2852, 0.8391, 0.9299, 0.0885, 0.6594, 0.1326, 0.2563,
         0.7079, 0.6505, 0.0451]])
torch.Size([1, 12])
tensor([[0.4885],
        [0.8982],
        [0.2852],
        [0.8391],
        [0.9299],
        [0.0885],
        [0.6594],
        [0.1326],
        [0.2563],
        [0.7079],
        [0.6505],
        [0.0451]])
torch.Size([12, 1])


## Concatenation operation

In [42]:
t14 = torch.zeros(2,2)
print(t14)
t15 = torch.ones(2,2)
print(t15)

# Concatenating along first axis/dimension (row-wise for 2d Tensor)
t16 = torch.cat((t14,t15),dim=0)
print(t16)
print(t16.shape)

# Concatenating along second axis/dimension (column-wise for 2d Tensor)
t17 = torch.cat((t14,t15),dim=1)
print(t17)
print(t17.shape)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]])
torch.Size([4, 2])
tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])
torch.Size([2, 4])


## Stacking operation

In [49]:
t18 = torch.zeros(2,2)
print(t18)
t19 = torch.ones(2,2)
print(t19)
t20 = torch.rand(2,2)
print(t20)

# Stacking operation
t21 = torch.stack((t18,t19,t20))
print(t21)
print(t21.shape)

# Stacking along first axis/dimension
t22 = torch.stack((t18,t19,t20),dim=0)
print(t22)
print(t22.shape)

# Stacking along second axis/dimension
t23 = torch.stack((t18,t19,t20),dim=1)
print(t23)
print(t23.shape)

# Stacking along third axis/dimension
t24 = torch.stack((t18,t19,t20),dim=2)
print(t24)
print(t24.shape)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3749, 0.5546],
        [0.0469, 0.4357]])
tensor([[[0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[1.0000, 1.0000],
         [1.0000, 1.0000]],

        [[0.3749, 0.5546],
         [0.0469, 0.4357]]])
torch.Size([3, 2, 2])


## Flattening operation

In [53]:
# Flattening along first axis/dimension
print(t21.flatten(start_dim=0))
# Flattening along second axis/dimension
print(t21.flatten(start_dim=1))

tensor([0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.3749,
        0.5546, 0.0469, 0.4357])
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [0.3749, 0.5546, 0.0469, 0.4357]])


## Element-wise operations

In [60]:
t25 = torch.ones(2,2)
print(t25)
t26 = torch.rand(2,2)
print(t26)

# All arithmetic operations: +, -, *, %; add(), sub(), mul(), div()
print(t25+t26)
print(t25.add(t26))

# All logical operations: ==, =>, <=; eq, ge, le,
print(t25<=t26)
print(t25.le(t26))

# Some mathemathical functions like sqrt(), abs()l neg()
print(t25.neg())

# Arithmetic operation betwenn tensor variable and scalar: Becoz of Broadcasting
print(t25+2)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.0577, 0.7670],
        [0.9564, 0.0587]])
tensor([[1.0577, 1.7670],
        [1.9564, 1.0587]])
tensor([[1.0577, 1.7670],
        [1.9564, 1.0587]])
tensor([[False, False],
        [False, False]])
tensor([[False, False],
        [False, False]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[3., 3.],
        [3., 3.]])


## Reducing operations

In [61]:
print(t25.sum())
print(t25.mean())

tensor(4.)
tensor(1.)


## Accessing elements of tensor

In [62]:
print(t25.mean().item()) # Accessing the mean value from the output tensor

1.0


In [63]:
# Accessing the mean alog first axis/dimension and converting the result to list
print(t25.mean(dim=0).tolist())
print(type(t25.mean(dim=0).tolist()))
print(len(t25.mean(dim=0).tolist()))

[1.0, 1.0]
<class 'list'>
2


In [64]:
# Accessing the mean alog first axis/dimension and converting the result to numpy
print(t25.mean(dim=0).numpy())
print(type(t25.mean(dim=0).numpy()))
print(t25.mean(dim=0).numpy().dtype)
print(t25.mean(dim=0).numpy().shape)

[1. 1.]
<class 'numpy.ndarray'>
float32
(2,)


**References:**
* https://deeplizard.com/learn/video/v5cngxo4mIg
* https://www.learnopencv.com/pytorch-for-beginners-basics/
* https://adventuresinmachinelearning.com/pytorch-tutorial-deep-learning/
* https://pythonprogramming.net/introduction-deep-learning-neural-network-pytorch/